#!/bin/bash


export USER=alterwin
export HOME=/home/alterwin

cd /home/alterwin/files/alterhaus


# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# Example usage
# In this example it's used to run `npm install` if package.json changed and `bower install` if `bower.json` changed.
check_run package.json "npm install"
check_run bower.json "bower install"

gulp build

rm -rf /home/alterwin/web/beta.alterhaus.com/public_html/*
cp -R ../git /home/alterwin/web/beta.alterhaus.com/public_html/
cp -R dist/* /home/alterwin/web/beta.alterhaus.com/public_html/
